default_config:


#logger:
#  default: info
#  logs:
#    homeassistant.components.heos: debug
#    pyheos: debug


ssdp:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
   base_url: !secret base_url
   use_x_forwarded_for: true
   trusted_proxies: 127.0.0.1

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


media_player:
  - platform: samsungtv
    host: tizen.lan


switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      hinten_rechts:
        code_on: 1377617 # 10001 1 1
        code_off: 1377620 # 10001 1 0
      stehlampe:
        code_on: 1380689 # 10001 2 1
        code_off: 1380692 # 10001 2 0

pi_hole:
  host: 'pihole.lan'
  ssl: false
  verify_ssl: false

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key

sensor:
  - platform: cpuspeed
  - platform: mqtt
    state_topic: "sensors/rf/receiver"
    name: "RF Receiver"
  - platform: imap
    name: "Emails ungelesen (priv)"
    server: pagenotfound.de
    username: bh@pagenotfound.de
    password: !secret imap_pw
  - platform: dht
    name: "Sun angle"
    sensor: DHT22
    pin: 4
    monitored_conditions:
      - temperature
      - humidity

recorder:
  purge_keep_days: 5
  db_url: mysql://homeassistant:homeassistant@127.0.0.1:3306/homeassistant?charset=utf8


calendar:
  - platform: todoist
    token: !secret todoist_token

alexa:
  smart_home:

api:

heos:
  host: heos-bar.lan

discovery:

homeassistant:
    customize: !include customize.yaml

ifttt:
   key: !secret ifttt_key
